# Generated by Django 3.1.2 on 2020-12-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201218_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
